# Generated by Django 3.2 on 2021-05-17 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dealer_Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firm_name', models.CharField(max_length=35, unique=True)),
                ('code', models.CharField(blank=True, max_length=20)),
                ('auth_number', models.CharField(blank=True, max_length=20)),
                ('first_name', models.CharField(blank=True, max_length=20)),
                ('last_name', models.CharField(blank=True, max_length=20)),
                ('pd_open_date', models.DateField(blank=True, null=True)),
                ('address', models.CharField(blank=True, max_length=30)),
                ('city', models.CharField(blank=True, max_length=15)),
                ('taluka', models.CharField(blank=True, max_length=15)),
                ('district', models.CharField(blank=True, max_length=15)),
                ('state', models.CharField(blank=True, max_length=15)),
                ('pin_code', models.CharField(blank=True, max_length=6)),
                ('contact', models.CharField(max_length=15, unique=True)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('pan_number', models.CharField(blank=True, max_length=15)),
                ('GST_number', models.CharField(blank=True, max_length=20)),
                ('seed_license', models.CharField(blank=True, max_length=20)),
                ('pesticide_license', models.CharField(blank=True, max_length=20)),
                ('fertilizer_license', models.CharField(blank=True, max_length=20)),
                ('SD_receipt_code', models.CharField(blank=True, max_length=20)),
                ('SD_expected', models.CharField(blank=True, max_length=15)),
                ('SD_deposited', models.CharField(blank=True, max_length=15)),
                ('SD_receipt_date', models.DateField(blank=True, null=True)),
                ('SD_payment_type', models.CharField(blank=True, max_length=30)),
                ('exp_first_order', models.CharField(blank=True, max_length=30)),
                ('managed_by', models.CharField(max_length=20)),
                ('agreement_done', models.BooleanField(default=False)),
                ('gift_sent', models.BooleanField(default=False)),
                ('authorized', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='User_Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20, unique=True)),
                ('address', models.CharField(blank=True, max_length=30)),
                ('city', models.CharField(blank=True, max_length=15)),
                ('taluka', models.CharField(blank=True, max_length=15)),
                ('district', models.CharField(blank=True, max_length=15)),
                ('state', models.CharField(blank=True, max_length=15)),
                ('pin_code', models.CharField(blank=True, max_length=6)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('contact', models.CharField(blank=True, max_length=12)),
                ('e_verified', models.BooleanField(default=False)),
                ('position', models.CharField(blank=True, max_length=15)),
                ('manager', models.CharField(max_length=20)),
                ('authorized', models.BooleanField(default=False)),
                ('date_of_joining', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
