# Generated by Django 3.2 on 2021-05-10 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20, unique=True)),
                ('address', models.CharField(max_length=30)),
                ('city', models.CharField(max_length=15)),
                ('taluka', models.CharField(max_length=15)),
                ('district', models.CharField(max_length=15)),
                ('state', models.CharField(max_length=15)),
                ('pin_code', models.CharField(max_length=6)),
                ('date_of_birth', models.DateField(auto_now_add=True)),
                ('contact', models.CharField(max_length=12)),
                ('e_verified', models.BooleanField(default=False)),
                ('position', models.CharField(max_length=15)),
                ('manager', models.CharField(max_length=20)),
                ('authorized', models.BooleanField(default=False)),
                ('date_of_joining', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
